services:
  terraform:
    image: hashicorp/terraform:1.8.1
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    working_dir: /tf
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - TF_WORKSPACE=${TF_WORKSPACE}

  app:
    build:
      context: .
    command: >
      sh -c "
        pip install flake8 &&
        python manage.py flake8
      "
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=your_project.settings