name: Test and Lint

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
        description: 'Username for DockerHub auth'
      DOCKERHUB_TOKEN:
        required: true
        description: 'Token for DockerHub auth'

jobs:
  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUN_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
        
      - name: Python flake8
        run: docker compose run --rm app sh -c "python manage.py flake8"

